### ISSUE TITLE
Arduino IDE version

### ISSUE THREAD

**Issue by bbailleux** [Orange-OpenSource/oorobot#12]
Hello,
On Linux, using the default version of the Arduino IDE installed from official repositories for Ubuntu, it is impossible to build and run Oorobot code.

=> lot of compile errors and no way to fix them without heavily changing the code.

> Please: **add a note with recommendation for the minimal Arduino IDE version needed**.

As found on the [Arduino website](https://playground.arduino.cc/Linux/Ubuntu): the available version installed _via_ software center or `apt` (currently 1.0.5) is outdated.

With a manually installed version (currently: v1.8.7), everything works smoothly.

> Note: same [for Debian](https://playground.arduino.cc/Linux/Debian), at least.

**Comment by matthieusalvat** [comment]
Hi Benoit,

I close this issue because I explain in arduino/oorobot/README.md to download  the latest version of the IDE.

Matthieu
