### ISSUE TITLE
Comment améliorer la précision des déplacements du robot

### ISSUE THREAD

**Issue by openelearning** [Orange-OpenSource/oorobot#13]
Bonjour,

Félicitations pour ce robot, quelle excellente idée d'avoir utilisé le clavier et l'écran pour que les petits puissent l'utiliser facilement.

Je viens de l'imprimer en 3D, mais je n'arrive pas à avoir de bons résultats vis à vis d'un déplacement précis, par exemple sur les cases de 14cm en plateau de 4x6.
J'ai réalisé l'étape de callibration. Par exemple, en partant du bas du plateau, si je lui indique Avant Avant droite Avant Gauche Avant Avant AVant, il arrive avec un décallage d'une moitiée de case.

Avez-vous des bons résultats sur la précision du déplacement par clavier ? (ou alors vous avez aussi  un décalage d'une demi case par exemple avec l'instruction ci-dessus)

Je m'interroge sur les pistes pour améliorer la précision : 
A) On dirait qu'il y a une différence légère entre la rotation du moteur droit et gauche, du coup il tournerait un peu trop sur la doite, et pas assez sur la gauche, et en ligne droite il aurait tendance à dévier un peu. > proposer une calibration des 2 moteurs ?
B) Mettre des roues plus petites, mais ça serait plus lent.
C) Ce sont des moteurs de même modèle que ceux que vous utilisez, que j'avais acheté à des vendeurs différents à des dattes différentes. Peut-être que vous avez testé pas mal de vendeurs, et que le fait d'acheter exactement chez le même vendeur que vous donnerait des meilleurs résultats ?
D) Vous avez des idées d'autres pistes ?
E) Utiliser d'autres modèles de moteurs pas à pas lowcost ?

Merci !
Ghis

**Comment by matthieusalvat** [comment]
Bonjour,

Sur mes différentes versions du robot le plus gros problème de décalage sur les longs parcours est plutôt du au placement initial.

Du coup je penche pour la réponse "C" pour votre problème.

Après si le code Arduino ne vous fait pas peur vous pouvez mettre en dur un coefficient sur la vitesse d'un des moteurs pour compenser la dérive.
