### ISSUE TITLE
Montage crayon

### ISSUE THREAD

**Issue by mgenet** [Orange-OpenSource/oorobot#14]
Bonsoir,

Merci infiniment pour ce beau projet, un régal pour les enfants et les parents. Je ne suis pas sûr de comprendre comment monter le crayon sur le modèle imprimé en 3D. Est-ce documenté quelque part? Merci encore.

Martin

**Comment by matthieusalvat** [comment]
Bonjour Martin,

En effet sur mon modèle 3D il manque encore un emplacement pour fixer le servomoteur permettant de lever et baisser un crayon. Il y a bien le la version de Delphine Thibault http://www.tablettesetpirouettes.com/oorobot-a-lecole-elementaire/ mais je ne l'ai pas testée.

Je vais essayer de faire un support sommaire d'ici peu.

Matthieu
