### ISSUE TITLE
Mettre l'apk dans la section release ?

### ISSUE THREAD

**Issue by yduf** [Orange-OpenSource/oorobot#25]
Bonjour, 

l'apk est actuellement directement fournie dans el repos avec le code source.
Pourquoi ne pas utiliser les [release github](https://help.github.com/en/github/administering-a-repository/creating-releases) ?

**Comment by matthieusalvat** [comment]
Oui, très bonne idée.

C'est fait : https://github.com/Orange-OpenSource/oorobot/releases

Matthieu
