### ISSUE TITLE
APK introuvable

### ISSUE THREAD

**Issue by FabTangi** [Orange-OpenSource/oorobot#46]
sur la page 
https://github.com/Orange-OpenSource/oorobot#pilotage-avec-le-bluetooth
le lien 
https://orange-opensource.github.io/oorobot/apk/oorobot.apk
renvoi 404. Serait-il possible d'avoir accès à l'apk?

**Comment by matthieusalvat** [comment]
J'ai mis à jour le lien (https://github.com/Orange-OpenSource/oorobot/releases)
